### ISSUE TITLE
Can't Install extension

### ISSUE THREAD

**Issue by drandrew1983** [puemos/hls-downloader#328] opened 2024-04-07 19:48 UTC
**Describe the bug**
can't install on chrome latest version

**To Reproduce**
1. Go to 'extensions'
2. enable developer mode
3. drag and drop the zip file
4. error loading extension: Failed to load extension from: extension-archive.zip. Could not unzip extension for install.

**Expected behavior**
extension should be successfully installed
**Screenshots**
![Screenshot 2024-04-08 004651](https://github.com/puemos/hls-downloader/assets/33606175/acc84ed7-3cd6-4961-9048-9377ba299af5)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version Version 123.0.6312.106 (Official Build) (64-bit)

**Comment by Vangelis66** [comment] 2024-04-08 17:39
The latest version `4.0.1` of the extension as packaged in [extension-archive.zip](https://github.com/puemos/hls-downloader/releases/download/v4.0.1/extension-archive.zip)
 is "corrupted"/**unsuccessfully compiled** :disappointed: ; when the archive is being probed with **7-zip**, this is how it looks: 

![401](https://github.com/puemos/hls-downloader/assets/9669492/ac739461-5903-4c8c-afb8-fd249f219db5)

... i.e. **folder tree is wrong**, contents of the **last dir** in the tree are **incomplete** (several missing files :cry: ); compare the above with the [previous working release](https://github.com/puemos/hls-downloader/releases/download/v4.0.0/extension.zip) `4.0.0`:

![400](https://github.com/puemos/hls-downloader/assets/9669492/c02ac109-d134-405b-a3ba-b7b7dd002118)

Please fix and release a **proper** archive/CRX file :stuck_out_tongue_winking_eye: ; see also #327 (probably this one here being a dupe of that) ...

**Comment by puemos** [comment] 2024-04-08 21:18
Thanks! I'll fix that

**Comment by puemos** [comment] 2024-04-10 13:40
Fixed! thanks again @drandrew1983 @Vangelis66

**Closed by puemos** 2024-04-10 13:40 UTC
Labels: bug

**Comment by puemos** [comment] 2024-04-10 13:54
FYI crx is now available in [v4.0.1](https://github.com/puemos/hls-downloader/releases/tag/v4.0.1)
