### ISSUE TITLE
No audio on CBC

### ISSUE THREAD

**Issue by jonandeva** [puemos/hls-downloader#189] opened 2021-05-17 13:44 UTC
I've been trying to download some content from CBC Gem. This show, for example: https://gem.cbc.ca/media/kims-convenience/season-1/episode-1/38e815a-00ade4014dc. (Must be in Canada or use Canadian VPN to access). When I use HLS Downloader on Chrome to get it, it has great video quality, but there's no audio. It seems like the audio comes through as a separate stream. Is there any way to fix this via the extension?

**Comment by puemos** [comment] 2021-08-23 16:39
Thanks @jonandeva, duplicate of #23

**Closed by puemos** 2021-08-23 16:39 UTC
