### ISSUE TITLE
Remuxing separate audio and video streams?

### ISSUE THREAD

**Issue by daniel-toman** [puemos/hls-downloader#103] opened 2020-06-04 04:12 UTC
I'm a documentary film editor and often need to download news clips from news outlet websites. They almost always offer .m3u8 video playback. I am so excited to have found this extension with its excellent UI for selecting which quality of stream to download. I often work with assistants who help download these clips and this extension is perfect for them to use. However I found a shortcoming on a news video where the audio streams separately from the video. This extension only downloaded the video stream, but not the audio stream.

Here's the m3u8 in question for the video and audio together: https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2020/05/05/1733822019527/479732_hls/master.m3u8

From there in the extension, I picked the 1080 stream to download, which is: 
https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2020/05/05/1733822019527/479732_hls/CBSN_fusion_11419_2_meat-processing-plants-vow-to-ramp-up-coronavirus-precautions_video_479732_3000/stream.m3u8

The extension download the 1080 video stream, but did not download / remux the audio stream referenced in the original master.m3u8 file.

The audio stream is: 
https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2020/05/05/1733822019527/479732_hls/CBSN_fusion_11419_2_meat-processing-plants-vow-to-ramp-up-coronavirus-precautions_video_479732_aac_128/stream.m3u8

And the original web page for this video is:
https://www.cbsnews.com/news/coronavirus-usda-meat-inspectors-3-dead-covid-19/

Thanks for this great tool! And thanks for any help you can provide to make it work better with news sites like this one.

**Comment by daniel-toman** [comment] 2020-06-04 17:42
Another thought on this: if separate audio streams could be presented as an option to be downloaded, even if this extension can't do the remuxing, I could remux myself in MPEG Streamclip. If the extension at least offered a UI for downloading the audio stream, my assistants could download the separate audio and video streams, and I can put them back together as needed. Better than nothing!

**Comment by puemos** [comment] 2020-06-08 09:57
Hey @daniel-toman thanks for taking the time to open this issue, I try several times to add remux but I didn't manage to pull it off, may offering a way to download them separately could be a in-between solution, thanks!

**Comment by puemos** [comment] 2021-08-23 15:28
Duplicate of https://github.com/puemos/hls-downloader/issues/23

**Closed by puemos** 2021-08-23 15:28 UTC
Labels: enhancement, ui, ux
